---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution_version }}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - install
    - nano

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package install nano'
  package:
    state: 'present'
    name: "{{ package_name_nano }}"
  register: result_nano_install
  until: result_nano_install is succeeded
  retries: 3
  tags:
    - install
    - nano
